services:
  gateway-service:
    image: psup-gateway/gateway-service
    container_name: gateway_service
    ports:
      - "9999:9999"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - CONFIG_SERVER_URL=http://config-server:8888
      - CONFIG_SERVER_USERNAME:myUsername
      - CONFIG_SERVER_PASSWORD:mySecretPassword
      - EUREKA_URL=http://eureka-server:8761/eureka
      - ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
      - PRODUCT_SERVICE_URL=lb://PRODUCT-SERVICE
      - MANUFACTURE_SERVICE_URL=lb://MANUFACTURE-SERVICE
      - STORAGE_SERVICE_URL=lb://STORAGE-SERVICE
    networks:
      - psup-shared-net

networks:
  psup-shared-net:
    external: true