server:
  port: 9999
spring:
  application:
    name: GATEWAY_SERVICE
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/product-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: productCircuitBreaker
                fallbackUri: forward:/fallback/product-service
                statusCodes:
                  - INTERNAL_SERVER_ERROR
                  - GATEWAY_TIMEOUT
                  - BAD_GATEWAY
        - id: manufacture-service
          uri: http://localhost:8081
          predicates:
              - Path=/api/v1/manufacture-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: manufactureCircuitBreaker
                fallbackUri: forward:/fallback/manufacture-service
                statusCodes:
                  - INTERNAL_SERVER_ERROR
                  - GATEWAY_TIMEOUT
                  - BAD_GATEWAY
        - id: storage-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/storage-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: storageCircuitBreaker
                fallbackUri: forward:/fallback/storage-service
                statusCodes:
                  - INTERNAL_SERVER_ERROR
                  - GATEWAY_TIMEOUT
                  - BAD_GATEWAY
eureka:
  client:
    register-with-eureka: false
    enabled: false
resilience4j:
  circuitbreaker:
    instances:
      productCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 75
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
        record-exceptions:
          - java.lang.RuntimeException
          - java.io.IOException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException
      manufactureCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 75
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
        record-exceptions:
          - java.lang.RuntimeException
          - java.io.IOException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException
      storageCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 75
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
        record-exceptions:
          - java.lang.RuntimeException
          - java.io.IOException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException
  timelimiter:
    instances:
      productCircuitBreaker:
        timeout-duration: 2s
        cancel-running-future: true
      manufactureCircuitBreaker:
        timeout-duration: 2s
        cancel-running-future: true
      storageCircuitBreaker:
        timeout-duration: 2s
        cancel-running-future: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always